### ISSUE TITLE
config files location?

### ISSUE THREAD

**Issue by 1iv3** [moudey/Shell#110]
Maybe I'm just dumb, but I can't find anywhere in the docs that the .nss or config files are supposed to be stored, nor can I even find the program files so I'm just a confused idiot.  Hope that helps.  I do like the way it looks now though than before.

**Comment by moudey** [comment]
Hi @1iv3

On this [page](https://nilesoft.org/docs/get-started), the path of the configuration file is displayed, and I marked it a little earlier, so that it is clear.

Anyway, press `Shift `and `right-click` on the taskbar, you will find a submenu for Shell, in which you will find an item to open the configuration file.

![screenshot_20230119_044404](https://user-images.githubusercontent.com/39198/213343398-0d1ff21f-0f3c-45e7-b8ab-5fc18d1d2acc.png)

**Comment by 1iv3** [comment]
Neato! nice little app! Thanks!
