### ISSUE TITLE
shell.nss changed it's content without my permissions?

### ISSUE THREAD

**Issue by bigplayer-ai** [moudey/Shell#169]
Hey,
I had some scripting on shell.ss after restarting my PC, The content of the file changed and removed my commands. Is this a normal behavior? Am I missing something out?
Oh this happened after reinstalling the program. Next time when updating please save you shell.nss so you won't less your work like this.

**Comment by bigplayer-ai** [comment]
Oh this happened after reinstalling the program.

**Comment by moudey** [comment]
When updating, **Shell** overwrites the existing files. Next update I will back up the settings files.

**Comment by martin-rueegg** [comment]
Maybe it would be good to store the configuration files in one of the following locations (selected by the user during setup), rather than in the program folder:

- for all users on this current machine (default)
  `"%ProgramData%\Nilesoft Shell\"`
- for only the current user on current machine
  `"%LOCALAPPDATA%\Nilesoft Shell\"` (usually `%USERPROFILE%\AppData\Local`)
- for the current users on all machines in the current domain
  `"%APPDATA%\Nilesoft Shell\"` (usually `%USERPROFILE%\AppData\Roaming`)
- a custom directory chosen during installation.

The setting should probably be stored somewhere in the registry (e.g. under `HKLM\SOFTWARE\Nilesoft\Shell\`) when installed using `setup.exe`, so that after an update, the setting can be used as a default.

For the portable installations, the `-register` switch would accept an optional argument `-register [shell.nss]`, like so:

```
shell -register "C:\path\to\custom\config.nss" -restart
```

As such, this command could be used after an update to restore one's custom configuration.

Also, for the `scoop` setup, this might be used as a default to set to `%USERPROFILE%\scoop\persist\nilesoft-shell\shell.nss`.
