### ISSUE TITLE
Must restart File Explorer on restart for Shell to work

### ISSUE THREAD

**Issue by ABO896** [moudey/Shell#195]
As said in the title. Every since a few weeks I've had to restart file explorer from task manager every single time I restart my PC as otherwise the shell menus do not work.

**Comment by moudey** [comment]
Please refer to this topic #171

**Comment by ABO896** [comment]
> Please refer to this topic #171

Tried the commands given and the issue was not fixed. The only possible thing which I may have tampered with is I removed some background processes/services using the autoruns program. However (and I have checked) I did not disable any nilesoft shell services or registry entries.

**Comment by stancho44** [comment]
> > Please refer to this topic #171
> 
> Tried the commands given and the issue was not fixed. The only possible thing which I may have tampered with is I removed some background processes/services using the autoruns program. However (and I have checked) I did not disable any nilesoft shell services or registry entries.

I found a temporary solution and posted in the #171 topic
https://github.com/moudey/Shell/issues/171#issuecomment-1467883698

**Comment by Dadaji18** [comment]
This issue persists due to improper uninstall/install of Shell. I had this issue because of a faulty uninstall, which couldn't delete the <code>shell.dll</code> file as it was open in Windows Explorer. To fix this,
- Open cmd inside the Shell directory
- Open task manager
- Find the <code>Windows Explorer</code> task, right click and end task
- Now using cmd delete the <code>shell.dll</code> file
```cmd
del /f shell.dll
```
- Now using <code>Run new task</code> in Task Manager, create a task with the name <code>explorer.exe</code>
- (Restart the pc if needed) You should have your original right-click context menu
- Now you can install Shell and it should work just fine

**Comment by moudey** [comment]
This command returns all processes that use **Shell**
```
item(title='Process' cmd=msg("All processes that use Shell\n\n" + app.process))
```
