### ISSUE TITLE
Moving and Replacing Icon from the context menu

### ISSUE THREAD

**Issue by frenzureta** [moudey/Shell#335]
Question 1: Is there possibility to change icon of "Edit with Notepad++" and "7zip"?

Question 2: How can i move this "Scan with Windows Defender" to the main menu?

Question 3: Can i move "More Options" above "Properties?

![image](https://github.com/moudey/Shell/assets/101829852/d7c7c9c6-9309-4cae-9ca6-711ea94b2934)

**Comment by RubicBG** [comment]
answer to question 1: yes (see: https://nilesoft.org/docs/syntax/static)
answer to question 2: yes (try: in "\imports\static.nss" delete `item(mode=mode.multiple find='scan with' menu=title.more_options)` )
answer to question 3: yes

in order to give you the solutions I need to know which version of NS you are using
(you can also look at this: https://discord.com/channels/1106387012707168318/1142552812740423770/1142552812740423770)

**Comment by frenzureta** [comment]
Im currently using Shell 1.8.1

**Comment by frenzureta** [comment]
> answer to question 1: yes (see: https://nilesoft.org/docs/syntax/static) answer to question 2: yes (try: in "\imports\static.nss" delete `item(mode=mode.multiple find='scan with' menu=title.more_options)` ) answer to question 3: yes
> 
> in order to give you the solutions I need to know which version of NS you are using (you can also look at this: https://discord.com/channels/1106387012707168318/1142552812740423770/1142552812740423770)

I try method 2 but still the "Scan with Microsoft Defender" is still there. idont about the code but will try to learn can you please provide the codes above?
