### ISSUE TITLE
Version number error. Shell 1.94

### ISSUE THREAD

**Issue by dracp** [moudey/Shell#357]
Shell Canary 1.94, shows in Shell version (taskbar.nss) value 1.93

![231021 Shell canary 1 94_Error en Versión](https://github.com/moudey/Shell/assets/102802425/d9fb2d22-80db-46b9-9e1c-55c1fdbee0bc)

**Comment by RubicBG** [comment]
this isn't bad coding - it's left like this so you can see where the changes are:
- NS works only through the shell.dll file when it is registered in Windows
- in order to be able to register in Windows, you need a manager - in this case shell.exe
These two files refer to the same program, but are built independently - the Shell Canary version is a test version, and it shows which of the two files has the changes made.

And I'm like an alpha tester - it's the same for me
![image](https://github.com/moudey/Shell/assets/127151533/f4f212b0-3a2b-4902-b128-02a3170904bf)

**Comment by dracp** [comment]
Understood. Thanks.
