### ISSUE TITLE
Some other options from ExplorerPatcher is missing (Windows10 Taskbar)

### ISSUE THREAD

**Issue by justin-a30** [moudey/Shell#410]
Hello, is there anyway to get ExplorerPatcher's options to Shell? It seems missing all here on Windows 11 (on Windows 10 it shows fully)
Here is some examples
### Original Shell
![image](https://github.com/moudey/Shell/assets/51263008/58a660e9-6ba3-4e86-aa18-7e46ab860a9b)

### Nilesoft Shell (taskbar.nss modified)
![image](https://github.com/moudey/Shell/assets/51263008/21047b74-6d8f-447c-9aa6-6721a44df557) 

Well, I have done further search on Issues tab including open and closed
[On this post](https://github.com/moudey/Shell/issues/246), it seems useless after all because it's already integrated. Maybe new update ruined it? Or maybe due to Windows Build?
This is my Windows Build: Windows 11 23H2 - Build22631.3085

**Comment by RubicBG** [comment]
I think I can recreate all the missing commands - I'll try ExplorerPatcher on Sunday and write back

**Comment by CrazyWolf13** [comment]
> I think I can recreate all the missing commands - I'll try ExplorerPatcher on Sunday and write back

Any updates? Would love to see this as well.

**Comment by RubicBG** [comment]
https://nilesoft.org/forum/viewtopic.php?t=20

**Comment by CrazyWolf13** [comment]
> https://nilesoft.org/forum/viewtopic.php?t=20

Okay Thanks!
Do I have to create a new file in imports and paste that code there?

**Comment by RubicBG** [comment]
you can copy the code into an existing one: 
\imports\taskbar.nss
between `item(title=title.desktop image=icon.desktop cmd=command.toggle_desktop)` and `item(title=title.settings image=icon.settings(auto, image.color1) cmd='ms-settings:')`

**Comment by CrazyWolf13** [comment]
Sadly can't really test it because of #433 but thanks a lot!

> you can copy the code into an existing one: at the end of \imports\taskbar.nss - save and reload the app with Ctrl +Right Click

**Comment by justin-a30** [comment]
> item(type='taskbar' title="&Lock the taskbar" cmd=window.command(424))
> item(type='taskbar' title="&Lock all taskbars" cmd=window.command(425))

That's pretty cool, thanks! But is there any way to make it "minimal"? Like showing tick with options "Lock Taskbar"
eg.
✓ Lock taskbar 

*Sorry for typing like this, I can't get any accurate examples since I'm on the phone right now.

**Comment by RubicBG** [comment]
```JS
$reg_taskbarsize = 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
$is_locked = reg.get(reg_taskbarsize, 'TaskbarSizeMove')
item(title="&Lock the taskbar" checked=!is_locked cmd=window.command(424))
// or
item(title=if(is_locked, '&Lock the taskbar', '&Unlock the taskbar') image=if(is_locked, \uE19A, \uE19B) cmd=window.command(424))
```

**Comment by justin-a30** [comment]
> ```js
> $reg_taskbarsize = 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
> $is_locked = reg.get(reg_taskbarsize, 'TaskbarSizeMove')
> item(title="&Lock the taskbar" checked=!is_locked cmd=window.command(424))
> // or
> item(title=if(is_locked, '&Lock the taskbar', '&Unlock the taskbar') image=if(is_locked, \uE19A, \uE19B) cmd=window.command(424))
> ```

added at the end of the taskbar.nss file, but it doesn't work. i have tried ctrl + right click but it doesn't show up. any idea?

**Comment by RubicBG** [comment]
if you put the commands at the end of the taskbar.nss file, add `type="taskbar"` property in the `item( <<<here>>> )` so it knows where to show the commands

or

add the code inside `menu(where=@(this.count == 0) type='taskbar' image=icon.settings expanded=true) { <<<here>>> }`

**Comment by justin-a30** [comment]
> if you put the commands at the end of the taskbar.nss file, add `type="taskbar"` property in the `item( <<<here>>> )` so it knows where to show the commands
> 
> or
> 
> add the code inside `menu(where=@(this.count == 0) type='taskbar' image=icon.settings expanded=true) { <<<here>>> }`

Thanks! This is working. I also hope that the integration of StartAllBack/ExplorerPatcher would be fixed.

**Comment by RubicBG** [comment]
reload the app with `ctrl+right click` - I think that will do the trick

**Comment by justin-a30** [comment]
> reload the app with `ctrl+right click` - I think that will do the trick

last time:  no, full options still there
just logged in and try: full options still missing 

i guess that, integration issues?

**Comment by RubicBG** [comment]
I don't know where the cause of the problem is and I can't answer. NS has no integration issues (at least until Microsoft changes something in the taskbar again), but using a 3rd party app to improve the functionality and visualization of the taskbar can lead to a conflict with NS

imagine that each program wants to take full control over the same component from Shell at the same time, regardless of whether it is Windows, NS or some third-party app - two by two can be understood, all three at the same time almost never - this is just an example of what happens most often. It may not be that at all. 

![image](https://github.com/moudey/Shell/assets/127151533/105fb07b-579b-4f4f-b662-b0e68e87778c)
For testing and compatibility I have Start11, StartAllBack and ExplorerPatcher installed on this computer. I can stop one program and start the other. while they work separately, I personally have no conflict with the NS, but on the other hand I don't use them 24/7 to run into a problem like yours

instead of login-logout, try restarting explorer.exe

**Comment by justin-a30** [comment]
Update: so, guess that it is Windows' bug?
Well, I've tried frequently crashing explorer as fast as I can, and spam right click, what I get is
- At first, it looks like there's a full menu from StartAllBack with Shell themed
- When the background (aka wallpaper) initialized, the shell went back to normal, without any more options from StartAllBack/ExplorerPatcher
Do I need to submit the log?

**Comment by RubicBG** [comment]
You describe a process in which the loading of components (and their settings) from the shell does not happen at the same time, but one after the other - while only some components are loaded you get one context menu, after loading all - you get another context menu. The log file won't show anything significant because it's not a NS problem.

But you gave me an idea. try to repair system files.
I found this to save my typing:
https://www.youtube.com/watch?v=acxCueZ2dVQ

Also took screenshots of all StartAllBack and ExplorerPatcher settings panels, zipped them and sent them to me. I'll look into how they differ from mine - maybe some setting is causing the problem

**Comment by justin-a30** [comment]
After a while, it seems doesn't work
I've done:
- Reinstall Windows
- Check for corrupted files (it passed)
- Remove conflicting applications (EasyContext Menu, ExplorerPatcher,...)
For the configuration of StartAllBack, it is default

Any idea so far? On Windows 10, right clicking on taskbar will show everything
